# Development
@baseUrl=http://localhost:8000/api/v1
@token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwidXNlcm5hbWUiOiJ0ZXN0MSIsIm5hbWUiOiJUZXN0IFVzZXIiLCJwZXJtaXNzaW9ucyI6bnVsbCwiZXhwIjoxNjU3MzUyODM0fQ.jU5yp2y-3H-dxXP1hdDW-FYEYv5F9GhAVDCbafphUzI

## User
@username = test1
@password = password
@name=Test User 2
### register user
POST {{baseUrl}}/users/register HTTP/1.1
content-type: application/json

{
  "username": "{{username}}",
  "password": "{{password}}",
  "name": "{{name}}"
}

### login user
POST {{baseUrl}}/users/login HTTP/1.1
content-type: application/json

{
  "username": "{{username}}",
  "password": "{{password}}"
}


## Bike
### get all bikes
GET {{baseUrl}}/bikes HTTP/1.1
content-type: application/json
Authorization: Bearer {{token}}
### rent a bike
PATCH {{baseUrl}}/bikes/1/rent HTTP/1.1
content-type: application/json
Authorization: Bearer {{token}}

### return a bike
PATCH {{baseUrl}}/bikes/1/return HTTP/1.1
content-type: application/json
Authorization: Bearer {{token}}
