name: Main

on:
  push:
    branches:
      - main

jobs:
  frontend_pull_request:
    name: Frontend
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./frontend

    steps:
      - name: Checks out repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Node Environment
        uses: actions/setup-node@v1
        with:
          node-version: 16

      - name: Cache node modules
        id: cache
        uses: actions/cache@v2
        with:
          path: node_modules
          key: build-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            build-${{ hashFiles('**/yarn.lock') }}

      - name: Install dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        run: yarn install

      - name: Unit Tests
        run: TZ=UTC yarn test:coverage

      - name: Build
        run: yarn build

  api_pull_request:
    name: API
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./api


    steps:
      - name: Setup go environment
        uses: actions/setup-go@v3
        with:
          go-version: 1.18.x

      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Test
        run: go test ./...
